### ISSUE TITLE
0.4.1 Response corruption with timeout and lua script

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [twitter/twemproxy#404]
We've found an issue whereby Twemproxy seems to get into a situation where responses are corrupted and mixed incorrectly between clients. The issue seems to be triggered by evaluation of a lua script combined with a response timeout. After a request is times out (and the client receives an "-ERR Connection timed out" Redis response), subsequent requests can see partial responses from other clients requests.

The minimal example I've been able to create that exhibits the issue:

``` lua
    local id_counter_key = KEYS[1]
    local x_key = KEYS[2]
    local id = -1
    local id_key = ""
    local x = ARGV[1]
    if redis.call('exists', x_key) == 1 then
        return {err="10001"}
    end
    id = redis.call('incr', id_counter_key)
    id_key = 'test_data:' .. id
    redis.call('hset', id_key, 'id', id)
    redis.call('hset', id_key, 'x', x)
    redis.call('set', x_key, id)
    return id
```

Combined with a configuration like:

``` yaml
user:
  listen: 0.0.0.0:22120
  redis: true
  hash: fnv1a_64a
  distribution: ketama
  auto_eject_hosts: false
  timeout: 5000
  server_retry_timeout: 1000
  server_failure_limit: 1 
  servers:
   - redis.test.com:6379:1 server
```

The problem appears using eval or evalsha, I can't reproduce it without a lua script that times out. It is sufficient to force timeouts by setting the twemproxy pool timeout value sufficiently low (e.g. 10ms) to see the issue, but the issue has been seen with 'real' response timeouts of both 5 and 20 secs.

I am also only able to reproduce this when 2 cases hold:
- The script has a error-condition exit such as the one above if the key exists;
- And also there is a separate process making set and get commands through twemproxy that have data of the form "nn:nn:nn" e.g. "12:34:56".

A minimal example of that 'second process':

``` sh
while true
do
  echo
  date
  nslookup $ENDPOINT | grep Address: | tail -n+2
  echo -e "get test_counter\nset test `date +%H:%M:%S`\nget test" \
    | redis-cli -h $ENDPOINT -p $PORT

  sleep 1
done
```

I have been trying to get a minimal example together but struggling to reproduce the situation when there isn't a secondary client, but I will keep working on this on Monday to get to the bottom of this, but thought it was worth reporting now due to the severity.

Here is a Python script that should demonstrate the issue when run in conjunction with the above shell loop:

``` python
from multiprocessing import Process
import random
import signal
import sys
import time

from redis import StrictRedis, ResponseError


WORKER_DELAY_SECS = 0.0001
NUM_WORKERS = 10


SCRIPT = """
    local id_counter_key = KEYS[1]
    local x_key = KEYS[2]
    local id = -1
    local id_key = ""
    local x = ARGV[1]
    if redis.call('exists', x_key) == 1 then
        return {err="10001"}
    end
    id = redis.call('incr', id_counter_key)
    id_key = 'test_data:' .. id
    redis.call('hset', id_key, 'id', id)
    redis.call('hset', id_key, 'x', x)
    redis.call('set', x_key, id)
    return id
"""


def get_twemproxy_redis():
    return StrictRedis("localhost", 22120)


def worker():
    user_redis = get_twemproxy_redis()

    while True:
        try:
            x = random.randint(1, 1000)

            result = user_redis.eval(SCRIPT, 2, "test_counter_key", "test_data_key", x)
            int(result)

        except ResponseError as e:
            pass

        time.sleep(WORKER_DELAY_SECS)


def create_data():
    subprocesses = []
    for i in range(NUM_WORKERS):
        p = Process(target=worker, name="worker-{}".format(i))
        subprocesses.append(p)

    for p in subprocesses:
        p.start()


if __name__ == "__main__":
    create_data()
```

Within a few seconds of both scripts running:

```
(venv)root@app-test:/opt/app# python run_twemproxy_soak_test.py 
Process worker-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_twemproxy_soak_test.py", line 44, in worker
    int(result)
ValueError: invalid literal for int() with base 10: '-ERR Inv'
```

**Comment by tom-dalton-fanduel** [comment]
Update, found a more minimal example that fails immediately for me:

```python
from multiprocessing import Process
import signal
import sys
import time

from redis import StrictRedis, ResponseError


def get_twemproxy_redis():
    return StrictRedis("localhost", 22120)


def worker_get():
    TEST_BANANA_KEY = "test_banana"
    BANANAS = "bananas!"

    user_redis = get_twemproxy_redis()
    user_redis.set(TEST_BANANA_KEY, BANANAS)

    while True:
        try:
            result = user_redis.get(TEST_BANANA_KEY)
            assert result == BANANAS, "Expected {}, got {}".format(
                BANANAS, result)
            print "banana success"

        except ResponseError:
            pass


def worker_script():
    TEST_DATA_KEY = "test_data_key"
    SCRIPT = """
        local x_key = KEYS[1]
        local x = ARGV[1]
        if redis.call('exists', x_key) == 1 then
            return {err="keyalreadyexists"}
        end
        return x
    """

    user_redis = get_twemproxy_redis()

    while True:
        try:
            x = 1234
            result = user_redis.eval(SCRIPT, 1, TEST_DATA_KEY, x)
            assert int(result) == x, \
                "Expected {}, got {}".format(x, int(result))
            print "script success"

        except ResponseError:
            pass


subprocesses = []


def stop(signum=None, frame=None):
    for p in subprocesses:
        try:
            p.terminate()
        except Exception:
            pass
    sys.exit()


def run_test():
    signal.signal(signal.SIGHUP, stop)
    signal.signal(signal.SIGTERM, stop)
    signal.signal(signal.SIGINT, stop)

    subprocesses.append(Process(target=worker_get, name="worker_get"))
    subprocesses.append(Process(target=worker_script, name="worker_script"))

    for p in subprocesses:
        p.start()

    # Now wait for something to go wrong
    while True:
        for p in subprocesses:
            if not p.is_alive():
                print "Subprocess exited, stopping."
                time.sleep(0.1)
                stop()
        time.sleep(0.001)

if __name__ == "__main__":
    run_test()
```

```
(venv)root@userauth-test:/opt/userauth# python run_standalone_twemproxy_test.py 
Process worker_script:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 48, in worker_script
    assert int(result) == x, \
ValueError: invalid literal for int() with base 10: 'OK'

Subprocess exited, stopping.

Process worker_get:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 18, in worker_get
    user_redis.set(TEST_BANANA_KEY, BANANAS)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: Connection timed out
```

From the above traceback, it looks like the "OK" that should come back from the banana-set call is actually being returned as the response of the script, and the banana-set call is seeing the "-ERR connection timed out" response. This happens immediately on running the script, we don't see any successful iterations of the banana worker or the script worker at all. This is still with a 10ms timeout set to ensure we see an artificially high number of timeouts.

I'm going to see if I can reproduce this now with a debug build of twmeproxy.

**Comment by tom-dalton-fanduel** [comment]
Simplified the test case even further:

```python
from multiprocessing import Process
import signal
import sys
import time

from redis import StrictRedis, ResponseError


def get_twemproxy_redis():
    return StrictRedis("localhost", 22120)


def worker_get():
    TEST_BANANA_KEY = "test_banana"
    BANANAS = "bananas!"

    user_redis = get_twemproxy_redis()
    user_redis.set(TEST_BANANA_KEY, BANANAS)
    print "banana set"

    while True:
        try:
            result = user_redis.get(TEST_BANANA_KEY)
            assert result == BANANAS, "Expected {}, got {}".format(
                BANANAS, result)
            print "banana success"

        except ResponseError as e:
            if e.message == "Connection timed out":
                print "banana timeout"


def worker_script():
    SCRIPT = """return {err="keyalreadyexists"}"""

    user_redis = get_twemproxy_redis()

    while True:
        try:
            result = user_redis.eval(SCRIPT, 1, "dummy")
            raise Exception("Expected to error, returned {}".format(result))

        except ResponseError as e:
            if e.message == "Connection timed out":
                print "script timeout"
                continue

            assert e.message == "keyalreadyexists", \
                "Unexpected error '{}'".format(e.message)
            print "script success"


subprocesses = []


def stop(signum=None, frame=None):
    for p in subprocesses:
        try:
            p.terminate()
        except Exception:
            pass
    sys.exit()


def run_test():
    signal.signal(signal.SIGHUP, stop)
    signal.signal(signal.SIGTERM, stop)
    signal.signal(signal.SIGINT, stop)

    subprocesses.append(Process(target=worker_get, name="worker_get"))
    subprocesses.append(Process(target=worker_script, name="worker_script"))

    for p in subprocesses:
        p.start()

    # Now wait for something to go wrong
    while True:
        for p in subprocesses:
            if not p.is_alive():
                print "Subprocess exited, stopping."
                time.sleep(0.1)
                stop()
        time.sleep(0.001)

if __name__ == "__main__":
    run_test()
```

Results in variations on:

```
(venv)root@userauth-test:/opt/userauth# python run_standalone_twemproxy_test.py 
script timeout
script success

Process worker_script:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 41, in worker_script
    raise Exception("Expected to error, returned {}".format(result))
Exception: Expected to error, returned OK

Subprocess exited, stopping.

Process worker_get:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 18, in worker_get
    user_redis.set(TEST_BANANA_KEY, BANANAS)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/opt/userauth/venv/local/lib/python2.7/site-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: Connection timed out
```

So the ordering in this case seems to be:
1. Script runs but is timed out by twemproxy "script timeout"
2. Script runs successfully second time "script success"
3. Banana-set is run but *appears* to be timed out by twemproxy (ref worker_get traceback)
4. Script runs for the third time, but is given the "OK" result from banana-set (ref worker_script traceback)

**Comment by tom-dalton-fanduel** [comment]
The other ordering/case I have seen is:

```
(venv)root@userauth-test:/opt/userauth# python run_standalone_twemproxy_test.py 
banana set
banana success
[repeats ~ 100 times]
banana success
script success
banana success
Process worker_script:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
banana success
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 41, in worker_script
    raise Exception("Expected to error, returned {}".format(result))
Exception: Expected to error, returned -keyalre
banana success
Subprocess exited, stopping.
banana success
[worker_get continues to run]
```

In this case, the result of the script is set to the string "-keyalre", rather than the script raising a ResponseException. No timeouts seem to have been involved in this case.

**Comment by charsyam** [comment]
@tom-dalton-fanduel Thanks. I will test it ASAP

**Comment by tom-dalton-fanduel** [comment]
I thought the key to this was a combination of response timeouts and lua script response parsing, but I'm now wondering if it's only related to parsing error responses.

**Comment by tom-dalton-fanduel** [comment]
```
(venv)root@userauth-test:/opt/userauth# python run_standalone_twemproxy_test.py 
banana set
banana timeout
script success
banana success
Process worker_script:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 41, in worker_script
    raise Exception("Expected to error, returned {}".format(result))
Exception: Expected to error, returned -keyalre
banana success
banana success
banana success
Subprocess exited, stopping.
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
banana success
(venv)root@userauth-test:/opt/userauth# 
```

Results in debug output: http://pastebin.com/y63yn4qB

**Comment by tom-dalton-fanduel** [comment]
Looks like the code was masking an additional "Invalid arguments" response error that I think comes from twemproxy falling back if it can't parse a response? Test code fixed:

```python
from multiprocessing import Process
import signal
import sys
import time

from redis import StrictRedis, ResponseError


def get_twemproxy_redis():
    return StrictRedis("localhost", 22125)


def worker_get():
    TEST_BANANA_KEY = "test_banana"
    BANANAS = "bananas!"

    user_redis = get_twemproxy_redis()
    user_redis.set(TEST_BANANA_KEY, BANANAS)
    print "banana set"

    while True:
        try:
            result = user_redis.get(TEST_BANANA_KEY)
            assert result == BANANAS, "Expected {}, got {}".format(
                BANANAS, result)
            print "banana success"

        except ResponseError as e:
            if e.message == "Connection timed out":
                print "banana timeout"
                continue

            raise Exception("Unexpected error {}".format(e))


def worker_script():
    SCRIPT = """return {err="keyalreadyexists"}"""

    user_redis = get_twemproxy_redis()

    while True:
        try:
            result = user_redis.eval(SCRIPT, 1, "dummy")
            raise Exception("Expected to error, returned {}".format(result))

        except ResponseError as e:
            if e.message == "Connection timed out":
                print "script timeout"
                continue

            assert e.message == "keyalreadyexists", \
                "Unexpected error '{}'".format(e.message)
            print "script success"


subprocesses = []


def stop(signum=None, frame=None):
    for p in subprocesses:
        try:
            p.terminate()
        except Exception:
            pass
    sys.exit()


def run_test():
    signal.signal(signal.SIGHUP, stop)
    signal.signal(signal.SIGTERM, stop)
    signal.signal(signal.SIGINT, stop)

    subprocesses.append(Process(target=worker_get, name="worker_get"))
    subprocesses.append(Process(target=worker_script, name="worker_script"))

    for p in subprocesses:
        p.start()

    # Now wait for something to go wrong
    while True:
        for p in subprocesses:
            if not p.is_alive():
                print "Subprocess exited, stopping."
                time.sleep(0.1)
                stop()
        time.sleep(0.001)

if __name__ == "__main__":
    run_test()
```

Results in output:

```
(venv)root@userauth-test:/opt/userauth# python run_standalone_twemproxy_test.py 
banana set
banana timeout
script timeout
banana timeout
script timeout
banana success
script success

Process worker_get:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 33, in worker_get
    raise Exception("Unexpected error {}".format(e))
Exception: Unexpected error Invalid argument

Subprocess exited, stopping.

Process worker_script:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "run_standalone_twemproxy_test.py", line 44, in worker_script
    raise Exception("Expected to error, returned {}".format(result))
Exception: Expected to error, returned -ERR Con
```

Debug output for the above: http://pastebin.com/tDWuE7H2

**Comment by tom-dalton-fanduel** [comment]
I think this is the key area:

```
We've now got msg 8 (eval script) and msg 10 (get banana) outstanding 


[2015-08-24 03:22:45.337] nc_connection.c:346 recv on sd 8 14 of 16317
[2015-08-24 03:22:45.337] nc_redis.c:2240 parsed rsp 11 res 0 type 133 state 0 rpos 23 of 33
00000000  2d 6b 65 79 61 6c 72 65  61 64 79 65 78 69 73 74   |-keyalreadyexist|
00000010  73 0d 0a 24 38 0d 0a 62  61 6e 61 6e 61 73 21 0d   |s..$8..bananas!.|
00000020  0a                                                 |.|
[2015-08-24 03:22:45.337] nc_util.c:235 malloc(16384) at 0x1a61420 @ nc_mbuf.c:46
[2015-08-24 03:22:45.337] nc_mbuf.c:99 get mbuf 0x1a653f0
[2015-08-24 03:22:45.337] nc_mbuf.c:257 split into mbuf 0x1a613e0 len 23 and nbuf 0x1a653f0 len 10 copied 10 bytes
[2015-08-24 03:22:45.337] nc_util.c:235 malloc(440) at 0x1a55f10 @ nc_message.c:207
[2015-08-24 03:22:45.337] nc_util.c:235 malloc(32) at 0x1a560d0 @ nc_array.c:29
[2015-08-24 03:22:45.337] nc_util.c:235 malloc(16) at 0x1a56100 @ nc_array.c:34
[2015-08-24 03:22:45.337] nc_message.c:320 get msg 0x1a55f10 id 12 request 0 owner sd 8
[2015-08-24 03:22:45.337] nc_mbuf.c:182 insert mbuf 0x1a653f0 len 10
[2015-08-24 03:22:45.337] nc_message.c:190 delete msg 8 from tmo rbt


Looks like we just parsed the response to msg 8 (script)


[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'out_queue' in pool 0 server 0
[2015-08-24 03:22:45.337] nc_stats.c:1166 decr field 'out_queue' to 1
[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'out_queue_bytes' in pool 0 server 0
[2015-08-24 03:22:45.337] nc_stats.c:1196 decr by field 'out_queue_bytes' to 31
[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'responses' in pool 0 server 0
[2015-08-24 03:22:45.337] nc_stats.c:1151 incr field 'responses' to 5
[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'response_bytes' in pool 0 server 0
[2015-08-24 03:22:45.337] nc_stats.c:1181 incr by field 'response_bytes' to 70


INVALID ARG RESPONSE FOR GET BANANA 4
Looks like the msg/buf start of "$8\r\n" has been lost?


[2015-08-24 03:22:45.337] nc_redis.c:2250 parsed bad rsp 12 res 1 type 0 state 0
00000000  62 61 6e 61 6e 61 73 21  0d 0a                     |bananas!..|
[2015-08-24 03:22:45.337] nc_core.c:198 recv on s 8 failed: Invalid argument
[2015-08-24 03:22:45.337] nc_core.c:237 close s 8 '172.16.5.48:6379' on event 00FF eof 0 done 0 rb 80 sb 239: Invalid argument
[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'server_connections' in pool 0 server 0
[2015-08-24 03:22:45.337] nc_stats.c:1166 decr field 'server_connections' to 0
[2015-08-24 03:22:45.337] nc_stats.c:1134 metric 'server_err' in pool 0 server 0
```

We serve an Invalid argument error back, but then later on when we get a response timeout, the client sees "-ERR Con". My guess is that something to do with [mis-]parsing the concatenated script error and get response results in some state being corrupted, meaning subsequent requests (which are on a new connection) are affected.

**Comment by tom-dalton-fanduel** [comment]
I think I've found the issue, I think it might be a bug in `redis_parse_rsp`.

Most errors that twemproxy deals with are on the form "-ERR blah blah blah".
I think the bug is here:
https://github.com/twitter/twemproxy/blob/master/src/proto/nc_redis.c#L1814

We're iterating over the characters in the message, and when we find a space or a CR we then fast-forward to the CR at the end of the message. But this means if the error message has no speace (e.g. our script's "-keyalreadyexists\r\n" message, then the erorr-parser swallows the first \r and we overrin into the following message's number-of-bytes part.

E.g. in the above example, 

```00000000  2d 6b 65 79 61 6c 72 65  61 64 79 65 78 69 73 74   |-keyalreadyexist|
00000010  73 0d 0a 24 38 0d 0a 62  61 6e 61 6e 61 73 21 0d   |s..$8..
```
Is what twemproxy is parsing as the error response - e.g. it also grabs the "$8\r\n" from the start of the second message.

I'll rebuild a debug version with an attempted fix now, and submit a PR if it works.

**Comment by charsyam** [comment]
@tom-dalton-fanduel Yes. you're right.
I also found it. and fixed it :)
but it's same with your code. :) only difference is position. :)(not important)

https://github.com/charsyam/twemproxy/commit/8001e66d6170a63fb88877cd28743bf41da286c2

+1
@manjuraj I think it is a simple solution :)

**Comment by tom-dalton-fanduel** [comment]
https://github.com/twitter/twemproxy/pull/406 opened with a fix.

**Comment by tom-dalton-fanduel** [comment]
It's not super relevant now, but there's an even more minimal example:

```
$ redis-cli
127.0.0.1:22120> EVAL 'return {err="x"}' 1 'notrelevant'
(error) ERR Connection timed out
(1.00s)
```

The eval command will always timeout, regardless of setting, because twemproxy is looking for the 'second' `\r\n` that never arrives.
